version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
    open-pull-requests-limit: 10
    reviewers:
      - peaky76
    assignees:
      - peaky76
    labels:
      - "dependencies"
    groups:
      dev-dependencies:
        dependency-type: development
